In [3]:
import pandas as pd

with open('FeMappingV9.json', encoding='utf-8') as inputfile:
    df = pd.read_json(inputfile)

In [4]:
df

,layer,MB,type,lpGBTs,modules
0,1,0,0,"[0, 1]","[{'u': 2, 'v': 0, 'elinks': [4, 0], 'shape': '..."
1,1,1,1,[2],"[{'u': 5, 'v': 0, 'elinks': [1], 'shape': 'F'}..."
2,1,2,0,[3],"[{'u': 4, 'v': 1, 'elinks': [2], 'shape': 'F'}..."
3,1,3,1,[4],"[{'u': 6, 'v': 1, 'elinks': [1], 'shape': 'F'}..."
4,1,4,0,[5],"[{'u': 3, 'v': 1, 'elinks': [3], 'shape': 'F'}..."
...,...,...,...,...,...
1276,50,0,11,[2163],"[{'u': 15, 'v': 7, 'elinks': [5], 'shape': 'f'}]"
1277,50,0,11,[2164],"[{'u': 15, 'v': 8, 'elinks': [5], 'shape': 'F'}]"
1278,50,0,11,[2165],"[{'u': 15, 'v': 9, 'elinks': [5], 'shape': 'F'}]"
1279,50,0,11,[2166],"[{'u': 15, 'v': 10, 'elinks': [5], 'shape': 'f'}]"
1280,50,0,11,[2167],"[{'u': 15, 'v': 11, 'elinks': [5], 'shape': 'F'}]"

In [5]:
df.to_csv('FEMappingV9.csv', encoding='utf-8', index=False)

In [7]:
df.to_csv('FEMappingV9.txt', header=None, index=None, sep=' ', mode='a')